### ISSUE TITLE
Week 2: Create deployable jupyter extension demoing soamc kibana metrics

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/maap-hec-aws#53]

**Comment by dylanwilbur** [comment]
# Description:
Create a jupyter extension which accesses and displays existing kibana metrics.

**Part 1: Develop**
1. Wrap the iframes received from the jupyter endpoints within a reverse proxy to bypass x-frame-options to allow for embeds
2. Embed these iframes within a jupyter extension

**Part 2: Deploy**
1. Host the reverse proxy in a way that can be accessed from within the live jupyter hub(maap-project.org)
2. Package the jupyter extension with npm so the extension can be accessed anywhere
3. Install the jupyter extension on the live maap project

DoD:

- [ ] User can access existing kibana metrics from the soamc endpoint within an arbitrary jupyter instance
- [ ] User can access existing kibana metrics from the soamc endpoint within the MAAP jupyter platform

**Comment by dylanwilbur** [comment]
**Bonus DoD**
- [ ] User can access any arbitrary kibana endpoint through the MAAP jupyter platform

**Comment by dylanwilbur** [comment]
Need to decide a name for the extension/npm package
