### ISSUE TITLE
R2: Metrics collection from ADES/WPST to ES/Kibana

### ISSUE THREAD

**Issue by jjacob7734** [MAAP-Project/maap-hec-aws#82]
Create job metrics in the ADES (PBS and K8s), collect them and ingest them into Elastic Search and Kibana visualization.

Definition of Done:
- [x] Metrics part of jobStatus payload from ADES PBS
- [x] Metrics part of jobStatus payload from ADES K8s
- [x] Metrics in ES
- [x] Metrics in Kibana visualization.
- [x] Documentation provided
- [x] Github repo commits provided
- [x] Live demo provided
